import React, { useState, useEffect } from 'react';
import {
  PlaySquare, AlertTriangle, Warehouse, Route, Sparkles,
  TrendingUp, TrendingDown, CheckCircle2, Clock, DollarSign,
  Activity, ArrowRight, Layers, ShieldAlert, RefreshCw
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer,
  CartesianGrid, Legend
} from 'recharts';
import { api } from '../services/api';
import { ScenarioSimulationResult } from '../types';

export const WhatIfSimulatorPage: React.FC = () => {
  const [scenarioType, setScenarioType] = useState<'close_highway' | 'new_logistics_hub' | 'new_road_corridor'>('close_highway');
  const [selectedRoad, setSelectedRoad] = useState('NH-6 (Shillong-Silchar Mountain Highway)');
  const [selectedHub, setSelectedHub] = useState('Silchar Multi-Modal Terminal (Cachar, Assam)');
  const [selectedHubCapacity, setSelectedHubCapacity] = useState<number>(5000);
  const [newRoadStart, setNewRoadStart] = useState('Guwahati');
  const [newRoadEnd, setNewRoadEnd] = useState('Tura (Direct Greenfield Corridor)');
  const [newRoadDist, setNewRoadDist] = useState<number>(145.0);

  const [simResult, setSimResult] = useState<ScenarioSimulationResult | null>(null);
  const [loading, setLoading] = useState(false);

  const runSimulation = async (type?: 'close_highway' | 'new_logistics_hub' | 'new_road_corridor') => {
    const activeType = type || scenarioType;
    setLoading(true);
    try {
      const res = await api.runSimulation({
        scenario_type: activeType,
        road_name: selectedRoad,
        hub_location: selectedHub,
        hub_capacity: selectedHubCapacity,
        start_point: newRoadStart,
        end_point: newRoadEnd,
        distance_km: newRoadDist
      });
      setSimResult(res);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    runSimulation('close_highway');
  }, []);

  // Format chart data for before vs after
  const chartData = simResult ? [
    {
      metric: "Transit Time (Hrs)",
      Before: simResult.before_metrics.average_transit_time_hrs || simResult.before_metrics.transit_duration_hrs || simResult.before_metrics.average_order_dispatch_time_hrs || 6.5,
      After: simResult.after_metrics.average_transit_time_hrs || simResult.after_metrics.transit_duration_hrs || simResult.after_metrics.average_order_dispatch_time_hrs || 11.2,
    },
    {
      metric: "Fuel/Freight Cost (₹k)",
      Before: simResult.before_metrics.average_fuel_cost_inr ? simResult.before_metrics.average_fuel_cost_inr / 1000 : 4.8,
      After: simResult.after_metrics.average_fuel_cost_inr ? simResult.after_metrics.average_fuel_cost_inr / 1000 : 7.9,
    },
    {
      metric: "Reliability / Spoilage",
      Before: simResult.before_metrics.corridor_reliability_index || simResult.before_metrics.spoilage_rate_perishables_pct || 82.0,
      After: simResult.after_metrics.corridor_reliability_index || simResult.after_metrics.spoilage_rate_perishables_pct || 38.0,
    }
  ] : [];

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-slate-800 pb-3">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <PlaySquare className="w-4 h-4 text-fuchsia-400" />
            <span className="text-xs font-bold text-fuchsia-400 uppercase tracking-widest font-mono">
              Policy & Infrastructure Impact Modeling
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            Infrastructure & Logistics Scenario Simulator
          </h1>
          <p className="text-xs text-slate-400 mt-0.5">
            Test policy decisions, highway cutoffs, hub deployments, and greenfield expressways before capital allocation.
          </p>
        </div>
      </div>

      {/* ⚠️ Mandatory Simulation Disclaimer Banner */}
      <div className="flex items-start gap-3 p-4 rounded-xl border border-amber-500/40 bg-amber-950/30 text-amber-300">
        <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5 text-amber-400" />
        <div className="text-xs leading-relaxed">
          <span className="font-black text-amber-300 uppercase tracking-wide">⚠ Simulation Mode Active — </span>
          All outputs generated by this tool are <strong>hypothetical scenario projections only</strong>.
          They are <strong>NOT confirmed government decisions</strong>, policy commitments, infrastructure approvals, or live operational data.
          Results are stored in the database with <code className="bg-amber-900/50 px-1 rounded">is_hypothetical = true</code>.
        </div>
      </div>

      {/* Scenario Selector Tabs */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        {/* Scenario 1 Tab */}
        <div
          onClick={() => {
            setScenarioType('close_highway');
            runSimulation('close_highway');
          }}
          className={`p-4 rounded-2xl border cursor-pointer transition-all ${
            scenarioType === 'close_highway'
              ? 'bg-red-950/40 border-red-500 glow-crimson shadow-xl scale-[1.02]'
              : 'glass-card border-slate-800 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center gap-2 font-bold text-sm text-red-400 mb-1">
            <AlertTriangle className="w-4 h-4" />
            <span>Scenario 1: Close Major Highway</span>
          </div>
          <p className="text-xs text-slate-400">
            Simulate emergency landslide closure on NH-6 or NH-10 and calculate network-wide delay surge.
          </p>
        </div>

        {/* Scenario 2 Tab */}
        <div
          onClick={() => {
            setScenarioType('new_logistics_hub');
            runSimulation('new_logistics_hub');
          }}
          className={`p-4 rounded-2xl border cursor-pointer transition-all ${
            scenarioType === 'new_logistics_hub'
              ? 'bg-sky-950/40 border-sky-500 glow-sky shadow-xl scale-[1.02]'
              : 'glass-card border-slate-800 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center gap-2 font-bold text-sm text-sky-400 mb-1">
            <Warehouse className="w-4 h-4" />
            <span>Scenario 2: Build Logistics Hub</span>
          </div>
          <p className="text-xs text-slate-400">
            Simulate deploying a new 5,000 MT multi-modal cold terminal in Barak Valley or Garo Hills.
          </p>
        </div>

        {/* Scenario 3 Tab */}
        <div
          onClick={() => {
            setScenarioType('new_road_corridor');
            runSimulation('new_road_corridor');
          }}
          className={`p-4 rounded-2xl border cursor-pointer transition-all ${
            scenarioType === 'new_road_corridor'
              ? 'bg-emerald-950/40 border-emerald-500 glow-emerald shadow-xl scale-[1.02]'
              : 'glass-card border-slate-800 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center gap-2 font-bold text-sm text-emerald-400 mb-1">
            <Route className="w-4 h-4" />
            <span>Scenario 3: Build Greenfield Expressway</span>
          </div>
          <p className="text-xs text-slate-400">
            Simulate constructing a high-speed direct highway (e.g. Guwahati ↔ Tura 145km).
          </p>
        </div>
      </div>

      {/* Interactive Parameter Controls */}
      <div className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-4">
        <h3 className="font-bold text-sm text-white">Scenario Parameters</h3>

        {scenarioType === 'close_highway' && (
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="sm:col-span-2">
              <label className="block text-[11px] font-semibold text-slate-300 mb-1">Select Road Corridor to Block</label>
              <select
                value={selectedRoad}
                onChange={(e) => setSelectedRoad(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white"
              >
                <option value="NH-6 (Shillong-Silchar Mountain Highway)">NH-6 (Shillong-Silchar Mountain Highway)</option>
                <option value="NH-10 (Sevoke-Teesta-Gangtok Corridor)">NH-10 (Sevoke-Teesta-Gangtok Corridor)</option>
                <option value="NH-29 (Dimapur-Kohima Corridor)">NH-29 (Dimapur-Kohima Corridor)</option>
                <option value="NH-37 (Jiribam-Imphal Lifeline)">NH-37 (Jiribam-Imphal Lifeline)</option>
              </select>
            </div>
            <div className="flex items-end">
              <button
                onClick={() => runSimulation()}
                disabled={loading}
                className="w-full bg-red-600 hover:bg-red-500 text-white font-bold py-2 px-4 rounded-xl text-xs h-[38px] transition-all shadow-lg flex items-center justify-center gap-1.5"
              >
                <PlaySquare className="w-4 h-4" />
                <span>{loading ? "Simulating..." : "Run Blockage Simulation"}</span>
              </button>
            </div>
          </div>
        )}

        {scenarioType === 'new_logistics_hub' && (
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="block text-[11px] font-semibold text-slate-300 mb-1">Hub Location</label>
              <select
                value={selectedHub}
                onChange={(e) => setSelectedHub(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white"
              >
                <option value="Silchar Multi-Modal Terminal (Cachar, Assam)">Silchar Multi-Modal Terminal (Assam)</option>
                <option value="Tura Agri-Logistics Center (West Garo Hills, Meghalaya)">Tura Agri-Logistics Center (Meghalaya)</option>
                <option value="Dimapur Rail-to-Road Freight Park (Nagaland)">Dimapur Rail Freight Park (Nagaland)</option>
              </select>
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-slate-300 mb-1">Target Capacity (MT)</label>
              <input
                type="number"
                value={selectedHubCapacity}
                onChange={(e) => setSelectedHubCapacity(parseFloat(e.target.value) || 5000)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white"
              />
            </div>
            <div className="flex items-end">
              <button
                onClick={() => runSimulation()}
                disabled={loading}
                className="w-full bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold py-2 px-4 rounded-xl text-xs h-[38px] transition-all shadow-lg flex items-center justify-center gap-1.5"
              >
                <PlaySquare className="w-4 h-4" />
                <span>{loading ? "Simulating..." : "Run Hub Simulation"}</span>
              </button>
            </div>
          </div>
        )}

        {scenarioType === 'new_road_corridor' && (
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <div>
              <label className="block text-[11px] font-semibold text-slate-300 mb-1">Corridor Origin</label>
              <input
                type="text"
                value={newRoadStart}
                onChange={(e) => setNewRoadStart(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white"
              />
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-slate-300 mb-1">Corridor Destination</label>
              <input
                type="text"
                value={newRoadEnd}
                onChange={(e) => setNewRoadEnd(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white"
              />
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-slate-300 mb-1">Engineered Length (km)</label>
              <input
                type="number"
                value={newRoadDist}
                onChange={(e) => setNewRoadDist(parseFloat(e.target.value) || 145)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white"
              />
            </div>
            <div className="flex items-end">
              <button
                onClick={() => runSimulation()}
                disabled={loading}
                className="w-full bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold py-2 px-4 rounded-xl text-xs h-[38px] transition-all shadow-lg flex items-center justify-center gap-1.5"
              >
                <PlaySquare className="w-4 h-4" />
                <span>{loading ? "Simulating..." : "Run Corridor Simulation"}</span>
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Simulation Result Output */}
      {simResult && (
        <div className="space-y-6">
          {/* 🔴 Per-Result Hypothetical Disclaimer */}
          <div className="flex items-center gap-3 p-3 rounded-xl border border-red-500/50 bg-red-950/30">
            <ShieldAlert className="w-5 h-5 text-red-400 shrink-0" />
            <p className="text-xs font-bold text-red-300 uppercase tracking-wide">
              {simResult.disclaimer || "SIMULATION RESULT — Hypothetical scenario, not a confirmed government project."}
            </p>
          </div>

          {/* Top 4 KPI Deltas */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="glass-panel p-4 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-semibold">Travel-Time Shift</span>
              <div className={`text-2xl font-black mt-1 ${simResult.travel_time_change_pct > 0 ? "text-red-400" : "text-emerald-400"}`}>
                {simResult.travel_time_change_pct > 0 ? `+${simResult.travel_time_change_pct}%` : `${simResult.travel_time_change_pct}%`}
              </div>
              <p className="text-[11px] text-slate-400 mt-1">Average Freight Latency</p>
            </div>

            <div className="glass-panel p-4 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-semibold">Freight Cost Impact</span>
              <div className={`text-2xl font-black mt-1 ${simResult.cost_change_pct > 0 ? "text-red-400" : "text-emerald-400"}`}>
                {simResult.cost_change_pct > 0 ? `+${simResult.cost_change_pct}%` : `${simResult.cost_change_pct}%`}
              </div>
              <p className="text-[11px] text-slate-400 mt-1">Per Trip Expenditure</p>
            </div>

            <div className="glass-panel p-4 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-semibold">Accessibility Delta</span>
              <div className={`text-2xl font-black mt-1 ${simResult.accessibility_change_points > 0 ? "text-emerald-400" : "text-red-400"}`}>
                {simResult.accessibility_change_points > 0 ? `+${simResult.accessibility_change_points}` : `${simResult.accessibility_change_points}`} pts
              </div>
              <p className="text-[11px] text-slate-400 mt-1">Regional Score Impact</p>
            </div>

            <div className="glass-panel p-4 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-semibold">Economic Impact (Est.)</span>
              <div className="text-base sm:text-lg font-black text-white mt-1 leading-snug">
                {simResult.economic_benefit_inr || "₹3.8 Crore / Year"}
              </div>
              <p className="text-[11px] text-sky-400 mt-1">{simResult.shipments_impacted} Convoys Affected</p>
            </div>
          </div>

          {/* AI Strategic Advice & Comparison Charts */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-6 glass-panel p-5 rounded-2xl border border-slate-800 space-y-4">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-sky-400" />
                <h3 className="font-bold text-sm text-white">AI Policy & Mitigation Advice</h3>
              </div>

              <div className="p-4 bg-slate-900/90 rounded-xl border border-slate-800 text-xs text-slate-200 leading-relaxed">
                «{simResult.ai_strategic_advice}»
              </div>

              <div>
                <h4 className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-2">
                  Impacted / Benefited Districts ({simResult.affected_districts.length}):
                </h4>
                <div className="flex flex-wrap gap-1.5">
                  {simResult.affected_districts.map((d, i) => (
                    <span key={i} className="text-xs bg-slate-800 text-slate-300 border border-slate-700 px-2.5 py-1 rounded-lg">
                      {d}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Before vs After Bar Chart */}
            <div className="lg:col-span-6 glass-panel p-5 rounded-2xl border border-slate-800">
              <h3 className="font-bold text-sm text-white mb-4">Before vs After Scenario Telemetry Comparison</h3>

              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={chartData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                    <XAxis dataKey="metric" stroke="#64748b" tick={{ fontSize: 10 }} />
                    <YAxis stroke="#64748b" tick={{ fontSize: 10 }} />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: 8, fontSize: 12 }} />
                    <Legend />
                    <Bar dataKey="Before" fill="#64748b" radius={[4, 4, 0, 0]} />
                    <Bar dataKey="After" fill={scenarioType === 'close_highway' ? '#ef4444' : '#10b981'} radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
